repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=50000000000000']
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      #   args:
      #   - --pattern=develop|main
      - id: requirements-txt-fixer
        args: [requirements.txt]
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.8.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0 # Update me!
    hooks:
      - id: bandit
        args:
        - --quiet
        - --format=custom
        - --configfile=bandit.yaml
  - repo: https://github.com/dhruvmanila/remove-print-statements
    rev: v0.5.2  # Replace with latest tag on GitHub
    hooks:
      - id: remove-print-statements
        args: ['--verbose']   # Show all the print statements to be removed
